# Generated by Django 3.1.5 on 2021-02-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('bodyText', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('product_type', models.CharField(max_length=50)),
                ('product_num', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='images/fundings/')),
                ('deadline', models.CharField(max_length=50)),
                ('community', models.CharField(max_length=100)),
                ('community_address', models.CharField(max_length=500)),
                ('current_product_num', models.IntegerField(default=0)),
            ],
        ),
    ]
