# Generated by Django 3.1.5 on 2021-02-05 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bodyText', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('product_type', models.CharField(max_length=50)),
                ('product_num', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='images/fundings/')),
                ('deadline', models.CharField(max_length=50)),
                ('community', models.CharField(max_length=100)),
                ('community_address', models.CharField(max_length=500)),
                ('current_product_num', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(blank=True, related_name='user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
