# Generated by Django 3.1.5 on 2021-02-03 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_auto_20210202_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='description',
            new_name='bodyText',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='funding_count',
            new_name='current_product_num',
        ),
        migrations.AddField(
            model_name='funding',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='community',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='community_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='deadline',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='product_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funding',
            name='product_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
